# Generated by Django 5.2.1 on 2025-06-01 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Novel Name/小说名称')),
                ('category', models.CharField(choices=[(1, '都市言情'), (2, '科幻小说'), (3, '悬疑推理'), (4, '历史小说'), (5, '武侠与修仙')], max_length=100, verbose_name='Novel Category/小说分类')),
                ('theme', models.CharField(max_length=300, verbose_name='Novel Theme/小说主题')),
                ('introduction', models.CharField(max_length=1000, verbose_name='Novel Introduction/小说简介')),
                ('remake', models.CharField(max_length=1000, verbose_name='Remake/备注')),
                ('word_count', models.IntegerField(default=0, verbose_name='Novel Word Count/总字数')),
                ('recommendation_num', models.IntegerField(default=0, verbose_name='Novel Recommendation Number/推荐数')),
                ('completed', models.BooleanField(default=False, verbose_name='Novel Completed/是否完结')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'novel',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('chapter_title', models.CharField(max_length=100, verbose_name='Chapter Title/本章标题')),
                ('chapter_text', models.TextField(verbose_name='Chapter Text/本章正文')),
                ('chapter_summary', models.TextField(max_length=300, verbose_name='Chapter Summary/本章簡述')),
                ('chapter_word_count', models.IntegerField(default=0, verbose_name='Chapter Word Count/本章字數')),
                ('chapter_role', models.CharField(max_length=100, verbose_name='Chapter Role/本章定位')),
                ('chapter_purpose', models.CharField(max_length=100, verbose_name='Chapter Purpose/核心作用')),
                ('suspense_level', models.CharField(max_length=100, verbose_name='Suspense Level/悬念密度')),
                ('foreshadowing', models.CharField(max_length=100, verbose_name='Foreshadowing/伏笔')),
                ('plot_twist_level', models.CharField(max_length=100, verbose_name='Plot Twist Level/认知颠覆')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novel.novel', verbose_name='Novel')),
            ],
            options={
                'db_table': 'chapter',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NovelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('core_seed', models.CharField(max_length=400, verbose_name='Core Seed/核心种子')),
                ('character_dynamics', models.CharField(max_length=5000, verbose_name='Character Dynamics/角色动力学')),
                ('world_view', models.CharField(max_length=5000, verbose_name='World View/世界观')),
                ('plot_architecture', models.CharField(max_length=5000, verbose_name='Plot Architecture/情节架构')),
                ('chapter_blueprint', models.CharField(max_length=5000, verbose_name='Chapter Blueprint/章节蓝图')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='novel.novel', verbose_name='Novel')),
            ],
            options={
                'db_table': 'novel_setting',
                'ordering': ['-id'],
            },
        ),
    ]
